### ISSUE TITLE
ghcr.io/downunderctf not found

### ISSUE THREAD

**Issue by jackfromeast** [DownUnderCTF/kube-ctf#2]
Hello team,

Firstly, a huge thank you for hosting DownUnderCTF this year. I thoroughly enjoyed participating. Kudos on the fantastic job!

I've been trying to emulate your solutions to set up isolated challenges for a CTF event. I've encountered a hurdle while deploying the challenge manager pods (step three in the README.md). I'm uncertain about the modifications needed in the helm chart.

1) Specifically, should I modify the following in chart/values.yaml?
```
kube-janitor:
  quota:
    limits:
      memory: 256Mi
    requests:
      cpu: 20m
      memory: 256Mi

challenge-manager:
  replicas: 3
  authSecret: keyboard-cat
  containerSecret: keyboard-cat
  registryPrefix: ghcr.io/downunderctf // error when pulling this image
  quota:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 125m
      memory: 256Mi

landing:
  replicas: 3
  quota:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 256Mi
```
Should I build the image for the challenge manager and landing page first and push them to the service before running the helm install?

2) Also, I couldn't locate this line in the `chart/values.yaml`? What should I put here?
```
containerRegistry: gcr.io/example # don't include the slash at the end
```

3) Should I replace the command in step 4 with the following line, since I didn't find the config folder?
```
helm install kubectf -f chart/values.yaml chart/
```

Thank you for your guidance.
